### ISSUE TITLE
Doesn't seem to work with RN 0.66

### ISSUE THREAD

**Issue by Relax594** [jhen0409/react-native-devsettings-android#18]
Getting building errors after updating to RN 0.66. No issues on RN 0.65.

![grafik](https://user-images.githubusercontent.com/22765758/135986619-93aedb68-3807-4016-a804-fa87b8579628.png)

**Comment by madflu9er** [comment]
@Relax594  Have the same issue, didnt find a sollution, so i just removed molude and removed imports where the error shows
