### ISSUE TITLE
React Native core PR

### ISSUE THREAD

**Issue by oblador** [jhen0409/react-native-devsettings-android#2]
Hey, 

Thanks for your work in this module, it works great! However I feel like this should be part of react-native core package as iOS already has this functionality. Couldn't find a PR addressing this, what's holding you back making one?

**Comment by oblador** [comment]
Ping @jhen0409

**Comment by jhen0409** [comment]
Sorry for delay.

The `DevSettings` implementation for Android have been landed in React Native v0.60 by https://github.com/facebook/react-native/pull/24441, so I'll close this issue.
